<a href="https://colab.research.google.com/github/AryanRaut14/NeuralNetworkfromScratch/blob/basic/NeuralNetworkfromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/AryanRaut14/BreastCancerDetection/main/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


Train Test Split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling


In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-0.24737419, -0.25416001, -0.2914967 , ..., -0.13986433,
        -1.06840002, -0.86907438],
       [ 0.2068339 , -1.08926314,  0.12480501, ..., -0.51688701,
        -0.9097712 , -1.32629789],
       [ 2.55542207,  1.75056199,  2.70122335, ...,  2.41089433,
         0.47462572,  0.20361985],
       ...,
       [ 0.05173845,  0.57619822,  0.08349569, ...,  0.46760308,
         1.10433405,  1.0082865 ],
       [ 0.94353726,  1.27844403,  0.98468062, ...,  0.88164802,
        -1.18857336,  0.51777852],
       [-0.70989097, -0.19959361, -0.73266423, ..., -0.73010505,
        -0.25923283, -1.12483925]])

In [ ]:
y_train

,diagnosis
464,B
511,B
202,M
156,M
59,B
...,...
84,B
147,B
36,M
168,M


Label Encoding

In [ ]:
#Since y has output in alphabet, we need to encode it into numeric values.
encoding = LabelEncoder()
y_train = encoding.fit_transform(y_train)
y_test = encoding.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,

NumPy to PyTorch

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape


torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

Define Model

In [ ]:
class MySimpleNN():

  def __init__(self, x):

    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
      z = torch.matmul(x , self.weights) + self.bias
      y_predicted = torch.sigmoid(z)
      return y_predicted

    #one of the possible approaches
    #def loss(self, y_predicted, y):
    #  loss = torch.mean((y - y_predicted))**2

  def loss_function(self, y_predicted, y):
      #clamp predictions to avoid log(0)
      epsilon = 1e-7
      y_predicted = torch.clamp(y_predicted, epsilon, 1-epsilon)

      #calculate loss
      loss = -(y_train_tensor * torch.log(y_predicted) + (1 - y_train_tensor) * torch.log(1 - y_predicted)).mean()
      return loss


Important parameters

In [ ]:
learning_rate = 0.1
epochs = 25

Traning pipeline

In [ ]:
# create model
model = MySimpleNN(x_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_predicted = model.forward(x_train_tensor)

  #calculate loss
  loss = model.loss_function(y_predicted, y_train_tensor)

  #backward pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradient initialize
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.857390329440918
Epoch: 2, Loss: 3.7299111800297355
Epoch: 3, Loss: 3.597262583317655
Epoch: 4, Loss: 3.4625781324850124
Epoch: 5, Loss: 3.3210045731780133
Epoch: 6, Loss: 3.1773892315860808
Epoch: 7, Loss: 3.028488300039572
Epoch: 8, Loss: 2.8741095391896168
Epoch: 9, Loss: 2.7142218481043456
Epoch: 10, Loss: 2.548419473067347
Epoch: 11, Loss: 2.379147977701356
Epoch: 12, Loss: 2.2036636148229736
Epoch: 13, Loss: 2.030731498742211
Epoch: 14, Loss: 1.8600734406485653
Epoch: 15, Loss: 1.6940753180737704
Epoch: 16, Loss: 1.5362670486726182
Epoch: 17, Loss: 1.383762060462379
Epoch: 18, Loss: 1.2472266134719057
Epoch: 19, Loss: 1.129107581263506
Epoch: 20, Loss: 1.0311684794384568
Epoch: 21, Loss: 0.9538256055694414
Epoch: 22, Loss: 0.895679522355544
Epoch: 23, Loss: 0.8536231004846355
Epoch: 24, Loss: 0.8237047252453885
Epoch: 25, Loss: 0.802221485578631


In [ ]:
model.weights

tensor([[-0.0267],
        [ 0.3023],
        [ 0.0227],
        [ 0.1738],
        [-0.2774],
        [-0.2102],
        [-0.6126],
        [-0.2097],
        [ 0.2756],
        [ 0.1154],
        [-0.0376],
        [ 0.3344],
        [-0.1166],
        [ 0.4052],
        [ 0.0671],
        [ 0.4426],
        [ 0.3672],
        [ 0.0153],
        [-0.1621],
        [ 0.4450],
        [ 0.2039],
        [-0.0751],
        [ 0.0325],
        [ 0.0791],
        [ 0.4793],
        [-0.1803],
        [-0.4028],
        [ 0.0357],
        [ 0.5508],
        [-0.2633]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1594], dtype=torch.float64, requires_grad=True)

Evaluation

In [ ]:
with torch.no_grad():
  y_prediction = model.forward(x_test_tensor)
  y_prediction = (y_prediction > 0.95).float()
  accuracy = (y_prediction == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5640196800231934
