<a href="https://colab.research.google.com/github/AryanRaut14/NeuralNetworkfromScratch/blob/basic/NeuralNetworkfromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/AryanRaut14/BreastCancerDetection/main/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


Train Test Split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling


In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
x_train

array([[ 0.05728347,  0.32159369,  0.05386871, ...,  0.30535718,
        -0.56897267, -0.29435866],
       [-1.75611765,  1.27687715, -1.76205399, ..., -1.69434997,
        -0.03018025, -0.74020744],
       [ 0.22623389, -0.36211293,  0.1955017 , ..., -0.45360561,
         1.13533808, -0.60628949],
       ...,
       [ 1.55812633, -0.06671356,  1.56774987, ...,  1.2626479 ,
         0.12490244,  0.83305626],
       [ 0.41207935,  1.13632422,  0.51876778, ...,  1.53594619,
         0.19684801,  1.23644325],
       [ 2.61125058,  0.68131389,  2.49020105, ...,  1.80924448,
         1.11775138,  0.42912489]])

In [9]:
y_train

,diagnosis
476,B
568,B
447,B
525,B
270,B
...,...
106,B
146,M
300,M
509,M


Label Encoding

In [10]:
#Since y has output in alphabet, we need to encode it into numeric values.
encoding = LabelEncoder()
y_train = encoding.fit_transform(y_train)
y_test = encoding.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

NumPy to PyTorch

In [12]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
x_train_tensor.shape


torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

Define Model

In [15]:
class MySimpleNN():

  def __init__(self, x):

    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
      z = torch.matmul(x , self.weights) + self.bias
      y_predicted = torch.sigmoid(z)
      return y_predicted

    #one of the possible approaches
    #def loss(self, y_predicted, y):
    #  loss = torch.mean((y - y_predicted))**2

  def loss_function(self, y_predicted, y):
      #clamp predictions to avoid log(0)
      epsilon = 1e-7
      y_predicted = torch.clamp(y_predicted, epsilon, 1-epsilon)

      #calculate loss
      loss = -(y_train_tensor * torch.log(y_predicted) + (1 - y_train_tensor) * torch.log(1 - y_predicted)).mean()
      return loss


Important parameters

In [16]:
learning_rate = 0.1
epochs = 25

Traning pipeline

In [17]:
# create model
model = MySimpleNN(x_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_predicted = model.forward(x_train_tensor)

  #calculate loss
  loss = model.loss_function(y_predicted, y_train_tensor)

  #backward pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradient initialize
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.0061056311242744
Epoch: 2, Loss: 2.853214893022062
Epoch: 3, Loss: 2.6938190784248324
Epoch: 4, Loss: 2.52877096204868
Epoch: 5, Loss: 2.3562960599737037
Epoch: 6, Loss: 2.1846067858020732
Epoch: 7, Loss: 2.0192515289998525
Epoch: 8, Loss: 1.8573928833792737
Epoch: 9, Loss: 1.7045554148734514
Epoch: 10, Loss: 1.5611559961667572
Epoch: 11, Loss: 1.4257654916272373
Epoch: 12, Loss: 1.3002704675287309
Epoch: 13, Loss: 1.1902280172539614
Epoch: 14, Loss: 1.0967837263507116
Epoch: 15, Loss: 1.020438366904385
Epoch: 16, Loss: 0.9605732215497669
Epoch: 17, Loss: 0.9152290554571006
Epoch: 18, Loss: 0.8815007376632465
Epoch: 19, Loss: 0.8563169029992155
Epoch: 20, Loss: 0.8370578764506603
Epoch: 21, Loss: 0.8217810994904315
Epoch: 22, Loss: 0.809167097037674
Epoch: 23, Loss: 0.798365000757697
Epoch: 24, Loss: 0.7888415343100685
Epoch: 25, Loss: 0.7802665846400061


In [18]:
model.weights

tensor([[-0.1922],
        [ 0.0521],
        [-0.3940],
        [ 0.4348],
        [ 0.3597],
        [-0.2798],
        [-0.2608],
        [-0.2173],
        [-0.1695],
        [-0.1004],
        [ 0.4401],
        [ 0.3091],
        [ 0.0258],
        [ 0.1308],
        [-0.1454],
        [-0.2678],
        [ 0.0373],
        [ 0.3433],
        [ 0.3245],
        [-0.1485],
        [ 0.3739],
        [ 0.5066],
        [-0.2959],
        [-0.3787],
        [ 0.1743],
        [-0.0122],
        [ 0.0767],
        [ 0.2441],
        [-0.0813],
        [ 0.0298]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([-0.2062], dtype=torch.float64, requires_grad=True)

Evaluation

In [20]:
with torch.no_grad():
  y_prediction = model.forward(x_test_tensor)
  y_prediction = (y_prediction > 0.95).float()
  accuracy = (y_prediction == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5877193212509155
